In [1]:
import numpy as np

# 数组

In [ ]:
l = [1, 2, 3, 4, 5]
print(l)
print(l[2])
print(l[-2])
print(l[1:3]) # 左闭右开
# print(l[[1,2]]) # 不支持

In [11]:
arr = np.array(l) # 创建数组
arr # available in jupyter
arr[[0, 2]] # 支持非连续取数组元素

array([3, 4, 5])

In [12]:
# 条件
cond = arr >= 3
cond
arr[cond]

array([3, 4, 5])

In [2]:
# 创建全是1的数组
np.ones(shape = 10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [3]:
# 创建全是0的数组
np.zeros(shape = 5)

array([0., 0., 0., 0., 0.])

In [4]:
# 创建指定元素填充的数组
np.full(shape=10, fill_value=20)

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [5]:
# 创建随机数组
np.random.randint(0, 100, size=10)

array([97, 16, 45, 47, 40, 17,  3, 74, 67, 36])

In [6]:
# 创建符合正态分布的数组
np.random.randn(10)

array([-0.07846451, -0.51687627,  1.99546989,  1.87220103, -0.31501118,
        0.73180705,  0.08536066, -2.23490235,  1.1513818 ,  0.72944873])

In [7]:
# 创建等差数列
np.linspace(1, 100, 100)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [14]:
# 创建等比数列
np.logspace(0, 10, base=2, num=11)

array([1.000e+00, 2.000e+00, 4.000e+00, 8.000e+00, 1.600e+01, 3.200e+01,
       6.400e+01, 1.280e+02, 2.560e+02, 5.120e+02, 1.024e+03])

In [16]:
# 不显示科学计数法
np.set_printoptions(suppress=True)
np.logspace(0, 10, base=2, num=11)

array([   1.,    2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,
        512., 1024.])

In [17]:
# 创建二维数组
np.random.randint(0, 10, size=(3, 5))

array([[7, 3, 0, 6, 5],
       [9, 3, 2, 3, 1],
       [0, 4, 5, 2, 6]])

In [3]:
arr = np.random.random(size=(3, 5))
# 查看数组的形状
arr.shape

(3, 5)

In [4]:
arr = np.random.random(size=(3, 5))
# 查看数组的元素类型
arr.dtype

dtype('float64')

In [5]:
arr = np.random.random(size=(3, 5))
# 查看数组的大小 多维数组的话维数要相乘
arr.size

15

In [6]:
arr = np.random.random(size=(3, 5))
# 查看数组的维数
arr.ndim

2

In [7]:
arr = np.random.random(size=(3, 5))
# 查看数组的元素类型大小
arr.itemsize

8

In [3]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# NumPy 数组运算
# 算术运算
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 3, 1, 5, 9])
print(arr1 - arr2) # arr1[i] - arr2[i]
print(arr1 + arr2) # arr1[i] + arr2[i]
print(arr1 * arr2) # arr1[i] * arr2[i]
print(arr1 / arr2) # arr1[i] / arr2[i]
print(arr1 ** arr2) # arr1[i] ** arr2[i]
print(arr1 < arr2) # arr1[i] < arr2[i]
print(arr1 + 5)
print(np.power(arr1, 2))
print(np.power(arr1, arr2))

[-1 -1  2 -1 -4]
[ 3  5  4  9 14]
[ 2  6  3 20 45]
[0.5        0.66666667 3.         0.8        0.55555556]
[      1       8       3    1024 1953125]
[ True  True False  True  True]
[ 6  7  8  9 10]
[ 1  4  9 16 25]
[      1       8       3    1024 1953125]


In [3]:
# 逻辑运算
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 3, 1, 5, 9])
print(arr1 <= arr2)
print(arr1 > arr2)
print(arr1 >= arr2)
print(arr1 == arr2)
print(arr1 != arr2)
print(arr1 > 5)

[ True  True False  True  True]
[False False  True False False]
[False False  True False False]
[False False False False False]
[ True  True  True  True  True]
[False False False False False]


In [21]:
# 索引
arr = np.random.randint(0, 100, 10)
print(arr)
print(arr[0])
print(arr[-1])
print(arr[[0, 2]]) # 取多个非连续元素
arr = np.random.randint(0, 100, [2, 10])
print(arr)
print(arr[0, 3])
print(arr[0, [2, 3]]) # 第一行第3个和第4个数据

[ 1 65 20 17 56  2  3 93 34 73]
1
73
[ 1 20]
[[30 95 62 36 74 99 76 70 64 60]
 [ 0 15 83 44 15  3 73 93 37 74]]
36
[62 36]


In [3]:
# 切片
arr = np.random.randint(0, 100, 10)
print(arr)
print(arr[3:6])
print(arr[3:6:2]) # 最后一个数指定步长
print(arr[::2]) # 不写表示默认
print(arr[::-1]) # 步长为负表示从后往前取
arr = np.random.randint(0, 100, [2, 10])
print(arr)
print(arr[[0, 1], 4:5])
print(arr[[0, 1], [0, 1]]) # 取(0,0) (1,1)
print(arr[[0, 1]][[0, 1], :])

[97 22  5 76 26 45 36 64 32 83]
[76 26 45]
[76 45]
[97  5 26 36 32]
[83 32 64 36 45 26 76  5 22 97]
[[54 57 10 54 69 51 92  2 99 84]
 [ 3 13 12 31 71 73 93 33 58 77]]
[[69]
 [71]]
[54 13]
[[54 57 10 54 69 51 92  2 99 84]
 [ 3 13 12 31 71 73 93 33 58 77]]


In [4]:
# 赋值
arr = np.random.randint(0, 100, [2, 2])
print(arr)
arr[0, 0] = 10248
print(arr)

[[ 8  0]
 [17 18]]
[[10248     0]
 [   17    18]]


In [10]:
arr = np.random.randint(0, 100, 10)
print(arr)
cond1 = (arr < 2) | (arr > 8)
print(arr[cond1])

[ 6 64 74 57  2 28 32 99 86 13]
[64 74 57 28 32 99 86 13]


# IO操作

In [5]:
# 保存数组
arr = np.arange(0, 10)
np.save("tmp/arr", arr)

In [7]:
# 载入数组
np.load("tmp/arr.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# 保存多个数据
arr = np.arange(0, 10)
arr2 = np.logspace(0, 10, 2, 11)
np.savez("tmp/multi-arr", arr, arr2)

In [13]:
# 从保存多个数组的文件中载入数据
np.load("tmp/multi-arr.npz")['arr_0']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 数据类型

In [16]:
# 创建时指定类型
np.array([1, 2, 3], dtype=np.int16)
np.random.randint(0, 10, size=(3, 5), dtype=np.int8)
np.arange(-128, 127, dtype=np.uint8)

C:\Users\poizi\AppData\Local\Temp\ipykernel_24104\2530799651.py:4: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -128 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  np.arange(-128, 127, dtype=np.uint8)
C:\Users\poizi\AppData\Local\Temp\ipykernel_24104\2530799651.py:4: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -127 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  np.arange(-128, 127, dtype=np.uint8)


array([128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
       141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
       154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166,
       167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179,
       180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192,
       193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205,
       206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218,
       219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231,
       232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244,
       245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255,   0,   1,
         2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  5

In [19]:
# 类型转换
arr = np.array([1, 2, 3], dtype=np.int16)
print(arr.dtype)
arr.astype(np.float64) # 生成了新数组
print(arr.dtype)

int16
int16
